//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameFramework_UILayersWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(GameFramework.UILayers));
		L.RegVar("Base", get_Base, null);
		L.RegVar("Backgroud", get_Backgroud, null);
		L.RegVar("Page", get_Page, null);
		L.RegVar("Window", get_Window, null);
		L.RegVar("NoMaskWindow", get_NoMaskWindow, null);
		L.RegVar("Message", get_Message, null);
		L.RegVar("Popup", get_Popup, null);
		L.RegVar("Emergent", get_Emergent, null);
		L.RegVar("King", get_King, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<GameFramework.UILayers>.Check = CheckType;
		StackTraits<GameFramework.UILayers>.Push = Push;
	}

	static void Push(IntPtr L, GameFramework.UILayers arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(GameFramework.UILayers), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Base(IntPtr L)
	{
		ToLua.Push(L, GameFramework.UILayers.Base);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Backgroud(IntPtr L)
	{
		ToLua.Push(L, GameFramework.UILayers.Backgroud);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Page(IntPtr L)
	{
		ToLua.Push(L, GameFramework.UILayers.Page);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Window(IntPtr L)
	{
		ToLua.Push(L, GameFramework.UILayers.Window);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NoMaskWindow(IntPtr L)
	{
		ToLua.Push(L, GameFramework.UILayers.NoMaskWindow);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Message(IntPtr L)
	{
		ToLua.Push(L, GameFramework.UILayers.Message);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Popup(IntPtr L)
	{
		ToLua.Push(L, GameFramework.UILayers.Popup);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Emergent(IntPtr L)
	{
		ToLua.Push(L, GameFramework.UILayers.Emergent);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_King(IntPtr L)
	{
		ToLua.Push(L, GameFramework.UILayers.King);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		GameFramework.UILayers o = (GameFramework.UILayers)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

