//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameFramework_UGUISpriteAnimationWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GameFramework.UGUISpriteAnimation), typeof(GameFramework.MonoBase));
		L.RegFunction("SetSprite", SetSprite);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSprite(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<UnityEngine.Sprite[]>(L, 2))
			{
				GameFramework.UGUISpriteAnimation obj = (GameFramework.UGUISpriteAnimation)ToLua.CheckObject<GameFramework.UGUISpriteAnimation>(L, 1);
				UnityEngine.Sprite[] arg0 = ToLua.ToObjectArray<UnityEngine.Sprite>(L, 2);
				obj.SetSprite(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<UnityEngine.Texture2D>(L, 2))
			{
				GameFramework.UGUISpriteAnimation obj = (GameFramework.UGUISpriteAnimation)ToLua.CheckObject<GameFramework.UGUISpriteAnimation>(L, 1);
				UnityEngine.Texture2D arg0 = (UnityEngine.Texture2D)ToLua.ToObject(L, 2);
				obj.SetSprite(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: GameFramework.UGUISpriteAnimation.SetSprite");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

