//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameFramework_CommonKeyWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("CommonKey");
		L.RegVar("URL_HOTUPDATE", get_URL_HOTUPDATE, null);
		L.RegVar("VERSION_LOCAL", get_VERSION_LOCAL, null);
		L.RegVar("VERSION_SERVER", get_VERSION_SERVER, null);
		L.RegVar("SWITCH_MUSIC", get_SWITCH_MUSIC, null);
		L.RegVar("SWITCH_AUDIO", get_SWITCH_AUDIO, null);
		L.RegVar("GAME_FRAME_RATE", get_GAME_FRAME_RATE, null);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_URL_HOTUPDATE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameFramework.CommonKey.URL_HOTUPDATE);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_VERSION_LOCAL(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameFramework.CommonKey.VERSION_LOCAL);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_VERSION_SERVER(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameFramework.CommonKey.VERSION_SERVER);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SWITCH_MUSIC(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameFramework.CommonKey.SWITCH_MUSIC);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SWITCH_AUDIO(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameFramework.CommonKey.SWITCH_AUDIO);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GAME_FRAME_RATE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameFramework.CommonKey.GAME_FRAME_RATE);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

