//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameFramework_IDModelWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GameFramework.IDModel), typeof(System.Object));
		L.RegFunction("New", _CreateGameFramework_IDModel);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("GetID", get_GetID, null);
		L.RegVar("GetLongId", get_GetLongId, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateGameFramework_IDModel(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				GameFramework.IDModel obj = new GameFramework.IDModel();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1)
			{
				string arg0 = ToLua.CheckString(L, 1);
				GameFramework.IDModel obj = new GameFramework.IDModel(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: GameFramework.IDModel.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GetID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameFramework.IDModel obj = (GameFramework.IDModel)o;
			string ret = obj.GetID;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GetID on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GetLongId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameFramework.IDModel obj = (GameFramework.IDModel)o;
			long ret = obj.GetLongId;
			LuaDLL.tolua_pushint64(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GetLongId on a nil value");
		}
	}
}

